import { Button, VerticalBox, StandardButton } from "std-widgets.slint";

export component Gif {
    property <int> current_frame;
    property <int> frame_count: 8;

    Timer {
        interval: 100ms;
        running: true;
        triggered => {
            current_frame += 1;
            if (current_frame == frame_count) {
                current_frame = 0;
            }
        }
    }

    Image {
        width: parent.width;
        height: parent.height;
        source: @image-url("res/images/sit.png");
        source-clip-x: 0;
        source-clip-y: current_frame * 1024;
        source-clip-height: 1024;
        source-clip-width: 1024;
    }
}

export component MessageDialog inherits Dialog {
    Text {
        text: "Message";
    }
    StandardButton {
        kind: ok;
        clicked => {
            root.close();
        }
    }
}

export component AppWindow inherits Window {
    no-frame: true;
    always-on-top: true;
    background: transparent;
    title: "安洁丽娜";
    width: 500px;
    height: 500px;

    property <bool> is_dragging: false;

    callback drag();
    callback start_drag();

    menu := PopupWindow {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;

        Rectangle {
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.6);
            border-radius: 20px;

            VerticalLayout {
                spacing: 5px;
                padding: 20px;

                Button {
                    text: "设置";
                }

                Button {
                    text: "退出";
                    clicked => {
                        root.close();
                    }
                }
            }
        }
    }

    TouchArea {
        width: 100%;
        height: 100%;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                menu.show();
            } else if (is_dragging && event.kind == PointerEventKind.move) {
                root.drag();
            } else if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                is_dragging = true;
                root.start_drag();
            } else if (is_dragging && event.kind == PointerEventKind.up && event.button == PointerEventButton.left) {
                is_dragging = false;
            }
        }
    }

    Gif {
        width: parent.width;
        height: parent.height;
    }
}