// Angelina desk pet.
// Copyright (C) 2026 CorvusCinereus
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Button, VerticalBox, StandardButton, ListView, StandardListView, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    no-frame: !show_frame;
    always-on-top: true;
    background: transparent;
    title: "安洁莉娜";
    width: size;
    height: size;
    forward-focus: key-handler;

    property <bool> is_dragging: false;
    property <bool> show_frame: false;
    in-out property <bool> playing: false;
    property <bool> loop: false;
    property <int> current_frame: 0;
    property <int> frame_count: 8;
    property <image> frame: @image-url("res/images/sit.png");
    in-out property <length> size: 500px;
    in-out property <[{index: int, path: string, name: string}]> musics;

    callback drag();
    callback start_drag();
    callback add_file();
    callback add_dir();
    callback play_music(index: int, path: string);
    callback stop_music();
    callback toggle_loop();

    menu := PopupWindow {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;

        Rectangle {
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.6);
            border-radius: 20px;

            VerticalLayout {
                spacing: 5px;
                padding: 20px;

                Button {
                    text: "听歌";
                    clicked => {
                        music_menu.show();
                    }
                }

                Button {
                    text: "设置";
                    clicked => {
                        menu.close();
                        settingmenu.show();
                    }
                }

                Button {
                    text: "退出";
                    clicked => {
                        root.close();
                    }
                }
            }
        }
    }

    music_menu := PopupWindow {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;

        Rectangle {
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.6);
            border-radius: 20px;

            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                ListView {
                    horizontal-stretch: 1;
                    for item in musics : Button {
                        text: item.name;
                        enabled: !root.playing;
                        clicked => {
                            root.play_music(item.index, item.path);
                            root.playing = true;

                            root.frame = @image-url("res/images/read.png");
                            root.frame_count = 7;
                            root.current_frame = 0;
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 10px;

                    Button {
                        text: "添加文件";
                        clicked => {
                            root.add_file();
                            music_menu.show();
                        }
                    }
                    Button {
                        text: "添加目录";
                        clicked => {
                            root.add_dir();
                            music_menu.show();
                        }
                    }
                }

                Button {
                    text: root.loop ? "单曲循环" : "列表循环";
                    clicked => {
                        root.loop = !root.loop;
                        root.toggle_loop();
                        music_menu.show();
                    }
                }

                Button {
                    text: "停止";
                    enabled: playing;
                    clicked => {
                        root.stop_music();
                        root.playing = false;

                        root.frame = @image-url("res/images/sit.png");
                        root.frame_count = 8;
                        root.current_frame = 0;
                    }
                }
            }
        }
    }

    settingmenu := PopupWindow {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;

        Rectangle {
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.6);
            border-radius: 20px;

            VerticalLayout {
                padding: 20px;
                spacing: 5px;

                HorizontalLayout {
                    spacing: 10px;

                    Text {
                        vertical-alignment: center;
                        text: "大小:";
                    }
                    Button {
                        text: "+";
                        clicked => {
                            root.size += 40px;
                            settingmenu.show();
                        }
                    }
                    Button {
                        text: "-";
                        clicked => {
                            root.size -= 40px;
                            settingmenu.show();
                        }
                    }
                }

                Button {
                    text: show_frame ? "隐藏边框" : "显示边框";
                    clicked => {
                        show_frame = !show_frame;
                    }
                }
            }
        }
    }

    key-handler := FocusScope {
       KeyBinding {
           keys: @keys(Escape);
           activated => {
               root.close();
           }
       }

       key-pressed(event) => {
           if (event.text == "+" || event.text == "=") {
               root.size += 40px;
           }
           if (event.text == "-") {
               root.size -= 40px;
           }
           accept
       }
    }

    TouchArea {
        width: 100%;
        height: 100%;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                menu.show();
            } else if (is_dragging && event.kind == PointerEventKind.move) {
                root.drag();
            } else if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                is_dragging = true;
                root.start_drag();
            } else if (is_dragging && event.kind == PointerEventKind.up && event.button == PointerEventButton.left) {
                is_dragging = false;
            }
        }
    }

    Timer {
        interval: 200ms;
        running: true;
        triggered => {
            current_frame += 1;
            if (current_frame == frame_count) {
                current_frame = 0;
            }
        }
    }

    Image {
        width: parent.width;
        height: parent.height;
        source: frame;
        source-clip-x: 0;
        source-clip-y: current_frame * 1024;
        source-clip-height: 1024;
        source-clip-width: 1024;
    }
}