// Angelina desk pet.
// Copyright (C) 2026 CorvusCinereus
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Button, VerticalBox, StandardButton } from "std-widgets.slint";

export component Gif {
    property <int> current_frame;
    property <int> frame_count: 8;

    Timer {
        interval: 200ms;
        running: true;
        triggered => {
            current_frame += 1;
            if (current_frame == frame_count) {
                current_frame = 0;
            }
        }
    }

    Image {
        width: parent.width;
        height: parent.height;
        source: @image-url("res/images/sit.png");
        source-clip-x: 0;
        source-clip-y: current_frame * 1024;
        source-clip-height: 1024;
        source-clip-width: 1024;
    }
}

export component SettingMenu {
    callback bigger();
    callback smaller();

    Rectangle {
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.6);
        border-radius: 20px;

        VerticalLayout {
            padding: 20px;
            spacing: 5px;

            HorizontalLayout {
                spacing: 10px;

                Text {
                    vertical-alignment: center;
                    text: "大小:";
                }
                Button {
                    text: "+";
                    clicked => {
                        root.bigger();
                    }
                }
                Button {
                    text: "-";
                    clicked => {
                        root.smaller();
                    }
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    no-frame: true;
    always-on-top: true;
    background: transparent;
    title: "安洁丽娜";
    width: size;
    height: size;

    property <bool> is_dragging: false;
    in-out property <length> size: 500px;

    callback drag();
    callback start_drag();
    callback save_config();

    menu := PopupWindow {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;

        Rectangle {
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.6);
            border-radius: 20px;

            VerticalLayout {
                spacing: 5px;
                padding: 20px;

                Button {
                    text: "设置";
                    clicked => {
                        menu.close();
                        settingmenu.show();
                    }
                }

                Button {
                    text: "退出";
                    clicked => {
                        root.close();
                    }
                }
            }
        }
    }

    settingmenu := PopupWindow {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;

        SettingMenu {
            bigger => {
                root.size += 40px;
                root.save_config();
            }
            smaller => {
                root.size -= 40px;
                root.save_config();
            }
        }
    }

    TouchArea {
        width: 100%;
        height: 100%;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                menu.show();
            } else if (is_dragging && event.kind == PointerEventKind.move) {
                root.drag();
            } else if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                is_dragging = true;
                root.start_drag();
            } else if (is_dragging && event.kind == PointerEventKind.up && event.button == PointerEventButton.left) {
                is_dragging = false;
            }
        }
    }

    Gif {
        width: parent.width;
        height: parent.height;
    }
}